# Generated by Django 3.1.7 on 2021-05-18 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticationSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rideHistory',
            new_name='paymentHistory',
        ),
        migrations.RenameModel(
            old_name='rider',
            new_name='propertyOwner',
        ),
        migrations.RenameModel(
            old_name='captain',
            new_name='renter',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
