# Generated by Django 3.1.7 on 2021-05-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0003_auto_20210518_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
    ]
