# Generated by Django 3.1.7 on 2021-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0005_auto_20210518_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='shopname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
